language: ruby
sudo: false
cache: bundler
services:
  - redis-server
rvm:
  - 2.2.8
  - 2.3.5
  - 2.4.2
  - ruby-head

gemfile:
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_edge.gemfile

matrix:
  exclude:
    - rvm: ruby-head
      gemfile: gemfiles/rails_42.gemfile

  include:
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/rails_42.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/rails_50.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/rails_51.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/rails_52.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-9.1.14.0
      gemfile: gemfiles/rails_edge.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-head
      gemfile: gemfiles/rails_42.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-head
      gemfile: gemfiles/rails_50.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-head
      gemfile: gemfiles/rails_51.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-head
      gemfile: gemfiles/rails_52.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data
    - rvm: jruby-head
      gemfile: gemfiles/rails_edge.gemfile
      jdk: oraclejdk8
      env: JRUBY_OPTS='--debug' # get more accurate coverage data

  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

  fast_finish: true

env:
  global:
    secure: LrTz0Pq2ibNZuKDhdzcrvEUSNxUpPopEq9aJeCxy3UpV0v4vpHBtWV0S6zofvf98g/RkZ6cGI1u+0H578dHgE6pWTo+iR8LAwqPKofrFIWRkeo+M77Vs5swahb3mQyPOcig1hfVWDm25MsojePYm70eBIcBU55NWImtdePXfiU0=
